apiVersion: v1
kind: Namespace
metadata:
  name: equezada
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: curso-devops-config
  namespace: equezada
data:
  USERNAME: "cmd"
  ENDPOINT: "http://api.google.com/v1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso-devops-deployment
  namespace: equezada
  labels:
    app: curso-devops-stack
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curso-devops-stack
  template:
    metadata:
      labels:
        app: curso-devops-stack
    spec:
      containers:
      - name: contenedor-curso-devops
        image: asparaguseduardo/curso-devops-lab3:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: curso-devops-service
  namespace: equezada
  labels:
    app: curso-devops-stack
spec:
  selector:
     app: curso-devops-stack
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: curso-devops-ingress
  namespace: equezada
spec:
  ingressClassName: nginx
  rules:
  - host: app.devops.cl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: curso-devops-service
            port:
              number: 80
