apiVersion: v1
kind: Namespace
metadata:
  name: curso
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso-devops-deployment
  namespace: curso
  labels:
    app: curso-devops-stack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: curso-devops-stack
  template:
    metadata:
      labels:
        app: curso-devops-stack
    spec:
      containers:
      - name: contenedor-curso-devops
        image: asparaguseduardo/curso-devops-lab3:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: curso-devops-service
  namespace: curso
  labels:
    app: curso-devops-stack
spec:
  selector:
     app: curso-devops-stack
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
